### ISSUE TITLE
Custom Output Area Component 

### ISSUE THREAD

**Issue by sarkartanmay393** [sarkartanmay393/GeoPulse#1]
Ideal Diagram: 

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/30705605-9212-4966-95bb-fce52b7ab670">

**Comment by sarkartanmay393** [comment]
Planning to use Accordion and Circular Charts by Shadcn.

1. https://ui.shadcn.com/docs/components/accordion
2. https://ui.shadcn.com/charts#radial-chart

**Comment by ghost** [comment]
Added initial components and packages. Now improvisation on existing components is required.

**Comment by sarkartanmay393** [comment]
We have a working component now. Closing this ticket.
