### ISSUE TITLE
Tooltip not working on mobile 📱

### ISSUE THREAD

**Issue by ghost** [sarkartanmay393/GeoPulse#10]
There are few tooltip on Output area. They support hover only but most touch screen devices don't have hover feature, that's why it is not working. If it can be done by tweaking existing component, that would be ideal. Otherwise it can use other packages.

<img width="795" alt="image" src="https://github.com/user-attachments/assets/1c8fd193-2496-40ff-9213-0dac80ef1bda">

**Comment by sarkartanmay393** [comment]
You can give it a shot @Nil2000

**Comment by Nil2000** [comment]
I was thinking of displaying the tooltip content just below the title. Obviously for the mobile screen only. Rest will be same as usual. What's your thought on this?

**Comment by sarkartanmay393** [comment]
@Nil2000 Yes, thanks for pointing out. Tooltip content should stay below the title always.

**Comment by Nil2000** [comment]
@sarkartanmay393 Please check your mail. I have few doubts.

**Comment by sarkartanmay393** [comment]
@Nil2000 Yes, already replied you. Do check please.

**Comment by Nil2000** [comment]
Was thinking of adding onClick event to this `<InfoCircledIcon/>` and below the title the tooltip content will be displayed but the accordion itself creating issue. If clicked on the icon the entire accordion shows up. Any better idea?

**Comment by ghost** [comment]
@Nil2000 Yes you can do that (onClick) but hovering should stay, just add onClick as an addition.  Inside the onClick function, you will receive an `event` props, do `e.stopPropagation()`

What it does basically, now if you click on Info icon, the click will not propagate outside of the onClick function. So I guess if you make the icon a little bigger, and click on it, the accordion will not open. Do try, may work, may not.

**Comment by Nil2000** [comment]
I did the following let me know if you want any more change
[geopulse_demo.webm](https://github.com/user-attachments/assets/e993ea21-4efb-4667-9c00-55783ce5603a)

**Comment by sarkartanmay393** [comment]
@Nil2000 I think there were not proper understanding of this ticket. You did good but tooltip should be like before. On click, a hover card with text should visible just like before. You need to just add onclick support on existing I button. Let's talk on Discord sometime.

**Comment by sarkartanmay393** [comment]
Removed tooltip for mobile. Now showing the tooltip text below accordion heading for mobile.
